const vi={
    mainTitle:"Chương trình giám sát hệ thống xử lý nước",
    logIn:"Đăng nhập",
    logOut:"Đăng xuất",
    messageToLogin:"Thông tin đăng nhập không hợp lệ",
    messageToLogout:"Phiên đăng nhập đã hết hạn, vui lòng đăng nhập lại!",
    username:"Tài khoản",
    password:"Mật khẩu",
    loca:"Vị trí: ",
    time:"Thời gian: ",
    len:"Mực nước ",
    pres:"Áp suất ",
    cloConcen:"Nồng độ Clo ",
    cloHist:"Lịch sử châm Clo",
    tableTime:"Thời gian",
    tableEmp:"Nhân viên",
    tableCloAmount:"Lượng Clo",
    addFormTitle:"Thêm lịch sử châm Clo",
    getDate:"Get",
    cloAmount:"Lượng Clo",
    save:"Lưu lại",
    yourData:"Dữ liệu đã nhập:",
    saveConfirm:"Thêm lịch sử châm Clo?",
    emptyValue:"Vui lòng nhập tên nhân viên!",
    falseAmount:"Lượng Clo nằm trong khoảng 50-1000!",
    created:"Dữ liệu đã được thêm!"
}

const en={
    mainTitle:"Water treatment monitoring program",
    logIn:"Log In",
    logOut:"Log out",
    messageToLogin:"Invalid login information",
    messageToLogout:"Login session has expired, please login again!",
    username:"Username",
    password:"Password",
    loca:"Location: ",
    time:"Time: ",
    len:"Water level ",
    pres:"Pressure ",
    cloConcen:"Chlorine concentration ",
    cloHist:"Chlorine injection list",
    tableTime:"Time",
    tableEmp:"Staff",
    tableCloAmount:"Amount of Chlorine",
    addFormTitle:"Chlorine injection",
    getDate:"Get",
    cloAmount:"Amount",
    save:"Save",
    yourData:"Your data:",
    saveConfirm:"Add Chlorine injection history?",
    emptyValue:"Staff name is empty!",
    falseAmount:"Amount is between 50 and 1000!",
    created:"Injection Created!"
}
export  {vi,en}